version: 2.1
orbs:
  yarn-berry: checkmoney/yarn-berry@1.0.0
  docker: checkmoney/docker@1.1.0
  deploy: checkmoney/deploy@1.2.1
workflows:
  version: 2
  build:
    jobs:
      - yarn-berry/local:
          name: eslint
          command: 'lint:code'
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - yarn-berry/local:
          name: types
          command: 'types'
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - docker/build_push:
          org_name: 'tripatrip'
          image_name: 'core-eat'
          image_version: CIRCLE_TAG
          docker_username: DOCKER_USERNAME
          docker_password: DOCKER_PASSWORD
          filters:
            branches:
              only: master
            tags:
              only: /.*/
          requires:
            - eslint
            - types
      - deploy/roll_out:
          notify_user: '-488110451'
          ssh_user: SSH_USER
          ssh_host: SSH_HOST
          org_name: 'tripatrip'
          image_name: 'view-telegram'
          image_version: CIRCLE_TAG
          path_to_app: PATH_TO_APP
          apply_post_install: true
          post_install_script: 'yarn evolutions -y'
          container_name: 'telegram_app'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - docker/build_push